
# ?? ??? ?? ??
server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  # DB ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://<host>:3306/likelion-db
    username: root
    password: <host>

  # JPA ??
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update